[options]
Architecture = auto
CheckSpace
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 1

[core]
Server = https://archive.archlinux.org/repos/2026/09/07/$repo/os/$arch

[extra]
Server = https://archive.archlinux.org/repos/2026/09/07/$repo/os/$arch
