monitor=,preferred,auto,1
input {
  kb_layout = us
  touchpad {
    natural_scroll = true
    tap-to-click = true
  }
}
general {
  gaps_in = 4
  gaps_out = 8
  border_size = 2
}
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
}
bind = SUPER, RETURN, exec, foot
bind = SUPER, C, killactive
exec-once = quickshell -p /usr/share/blossom-os/shell/quickshell.qml
