anchor=top-right
background-color=#171d27f2
border-color=#506987ff
border-radius=12
border-size=2
default-timeout=7000
font=Noto Sans 11
icons=1
layer=overlay
margin=14
padding=14
text-color=#f4f7fbff
width=380

[mode=do-not-disturb]
invisible=1
