monitor=,800x600@60,auto,1
animations {
    enabled = false
}
misc {
    disable_hyprland_logo = true
}
debug {
    disable_logs = false
    enable_stdout_logs = true
}
exec-once = env QML_IMPORT_PATH=/usr/lib/qt6/qml quickshell -p /usr/share/blossom-os/shell/shell.qml
